xmpp import broke
Would refuse to start with the following error:

```
Traceback (most recent call last):
  File "/opt/cloudprint/cloudprint/cloudprint.py", line 40, in <module>
    from cloudprint import xmpp
  File "/opt/cloudprint/cloudprint/cloudprint.py", line 40, in <module>
    from cloudprint import xmpp
ImportError: cannot import name xmpp
```
Updated code to the proposed, and it's alive!